trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
      - .gitignore
      - README.md

pr: none

pool:
  vmImage: 'windows-latest'

name: 3.0$(Rev:.r)

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Package'
  inputs:
    command: 'pack'
    packagesToPack: '**/EL.Http.csproj'
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  displayName: 'Publish'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '2ee1cde5-9787-4e91-b498-e30a43c5d914'
